version: "3.7"
services:
  django:
    build: ./backend
    volumes:
      - ./backend:/app/backend
      - ./docs:/app/docs
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.development
    stdin_open: true
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
  react:
    build: ./frontend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PATH=0
    depends_on:
      - django
    command: npm start
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /Applications/MAMP/htdocs/dr_test/backend:/app/backend
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: